name: Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install npm deps
        run: pnpm install --frozen-lockfile

      - name: Check the build
        run: pnpm run check

      - name: Code linting
        run: pnpm run lint

      - name: Check dependencies and unused files
        uses: oven-sh/setup-bun@v1
        run: bunx --bun knip
